
- name: download nodebrew
  sudo: yes
  shell: curl -L git.io/nodebrew | perl - setup

#- name: install nodebrew
#  command: perl /var/tmp/nodebrew setup

- name: install node.js latest
  ignore_errors: True
  shell: bash -lc "nodebrew install-binary latest"

- name: use node.js version
  shell: bash -lc "nodebrew use latest"

- name: install chromedriver
  shell: bash -lc "npm install -g chromedriver"

- name: Install global pm2
  shell: bash -lc "npm install -g pm2"


